# Generated by Django 4.2 on 2026-09-14 09:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contacts", "0005_rename_subcsription_donor_subscription"),
    ]

    operations = [
        migrations.AddField(
            model_name="donor",
            name="count_declined",
            field=models.PositiveSmallIntegerField(
                default=0, verbose_name="Счётчик неудачных платежей"
            ),
        ),
    ]
