# Generated by Django 4.2 on 2026-09-16 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0006_donor_count_declined'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donor',
            name='subscription',
            field=models.TextField(choices=[('ACTIVE', 'Подписка активна'), ('INACTIVE', 'Подписка отсутствует'), ('LOST', 'Подписка утрачена')], verbose_name='Статус подписки у донора'),
        ),
    ]
