# Generated by Django 5.2.17 on 2026-09-26 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0007_alter_donor_subscription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donor',
            name='subscription',
            field=models.TextField(choices=[('Active', 'Подписка активна'), ('Inactive', 'Подписка отсутствует'), ('Lost', 'Подписка утрачена')], verbose_name='Статус подписки у донора'),
        ),
    ]
