# Generated by Django 4.2 on 2026-09-14 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mixplat', '0002_alter_mixplat_donat'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mixplat',
            options={'ordering': ('-pub_date', 'status'), 'verbose_name': 'Платеж Mixplat', 'verbose_name_plural': 'Платежи Mixplat'},
        ),
    ]
