name : Test Crisis-center Workflow
on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.13.15"

      - name: Install Poetry
        run: |
          curl -sSL https://install.python-poetry.org | python3 -
          echo "PATH=$HOME/.local/bin:$PATH" >> $GITHUB_ENV

      - name: Install dependencies
        working-directory: ./backend
        run: |
          poetry install

      - name: Test with flake8
        working-directory: ./backend
        run: |
          poetry run flake8 --exclude=*/migrations/* .

      # - name: Test with pytest
      #   run: |
      #     poetry run pytest